#import "../template.typ": *

En la actualidad, los sistemas de recuperación de información (IR) enfrentan el desafío de predecir la calidad de los resultados de búsquedas, especialmente en consultas ad-hoc, donde la eficacia de los métodos de Query Performance Prediction (QPP) varía significativamente según el dominio y el tipo de consulta. Esta variabilidad puede derivar en respuestas subóptimas y un uso ineficiente de recursos, lo que subraya la necesidad de una evaluación robusta y reproducible de los métodos QPP más utilizados. Es así como, este proyecto, se enfoca en implementar y evaluar métodos QPP no basados en inteligencia artificial (IA) para búsquedas ad-hoc, utilizando métricas de correlación estandarizadas como Tau de Kendall, Spearman y Pearson, con el objetivo de establecer una línea base para futuras investigaciones y facilitar el desarrollo de nuevos enfoques.

De esta forma, el objetivo principal del proyecto es evaluar comparativamente métodos de QPP para búsquedas ad-hoc, identificando sus fortalezas y debilidades en diferentes contextos. Para ello, fueron seleccionados seis métodos QPP ampliamente reconocidos en la literatura: IDF (Inverse Document Frequency), SCQ (Similarity Between a Query and a Collection), NQC (Normalized Query Commitment), Clarity Score (CS), WIG (Weighted Information Gain) y UEF (Utility Estimation Framework), los cuales fueron implementados y evaluados en cinco datasets representativos (Cranfield, MS MARCO Passage, Antique/test, BEIR-TREC-COVID y CAR Judged), que abarcan una amplia gama de dominios y tipos de consultas, asegurando la generalización de los resultados.

Es así como el análisis de los resultados fue centrado en la comparación de las correlaciones entre los puntajes de los métodos QPP y las métricas de rendimiento del sistema de recuperación, en donde se revela que los métodos post-retrieval presentan las correlaciones más altas, superando significativamente a los métodos pre-retrieval como IDF, que presenta correlaciones cercanas a cero, adicional a esto, se observa que la implementación de UEF mejora considerablemente el rendimiento de los métodos post-retrieval.

Finalmente, los resultados del proyecto establecen una línea base sólida para la evaluación de métodos QPP en búsquedas ad-hoc, sin embargo, la complejidad propia de la tarea de predicción del rendimiento de consultas sigue siendo un desafío, lo que sugiere la necesidad de desarrollar métodos híbridos que combinen las fortalezas de diferentes enfoques. 
