#import "../template.typ": *

En la actualidad, los sistemas de recuperación de información (IR) enfrentan el desafío de predecir la calidad de los resultados de búsquedas, especialmente en consultas ad-hoc, donde la eficacia de los métodos de Query Performance Prediction (QPP) varía significativamente según el dominio y el tipo de consulta. Esta variabilidad puede derivar en respuestas subóptimas y un uso ineficiente de recursos, lo que subraya la necesidad de una evaluación robusta y reproducible de los métodos QPP más utilizados. Este trabajo de título, se enfoca en generar un marco de trabajo experimental basado en contenedores y bibliotecas de recuperación, para implementar y evaluar métodos QPP no basados en inteligencia artificial (IA) para búsquedas ad-hoc, utilizando métricas de correlación estandarizadas como Tau de Kendall, Spearman y Pearson, con el objetivo de establecer una línea base para futuras investigaciones y facilitar el desarrollo de nuevos enfoques.

En este sentido, el objetivo principal del trabajo es evaluar comparativamente métodos de QPP para búsquedas ad-hoc, identificando sus fortalezas y debilidades en diferentes contextos. Para ello, fueron seleccionados seis métodos QPP ampliamente reconocidos en la literatura: IDF (Inverse Document Frequency), SCQ (Similarity Between a Query and a Collection), NQC (Normalized Query Commitment), Clarity Score (CS), WIG (Weighted Information Gain) y UEF (Utility Estimation Framework), los cuales fueron implementados y evaluados en cinco datasets representativos (Cranfield, MS MARCO Passage, Antique/test, BEIR-TREC-COVID y CAR Judged), que abarcan una amplia gama de dominios y tipos de consultas, asegurando la generalización de los resultados.

Respecto al análisis de los resultados, este se centró en la comparación de las correlaciones entre los puntajes de los métodos QPP y las métricas de rendimiento del sistema de recuperación, revelando que los métodos post-retrieval presentan las correlaciones más altas, superando significativamente a los métodos pre-retrieval como IDF, que presenta correlaciones cercanas a cero (τ < 0.15). Asimismo, se observa que la implementación de UEF mejora considerablemente el rendimiento de los métodos post-retrieval, alcanzando coeficientes Tau de hasta 0.427 en colecciones como Antique.

Finalmente, los resultados establecen una línea base sólida para la evaluación de métodos QPP, mientras que el marco de desarrollo implementado garantiza la reproducibilidad de los experimentos. No obstante, la complejidad propia de la tarea de predicción sigue siendo un desafío, lo que sugiere la necesidad de desarrollar métodos híbridos que combinen las fortalezas de diferentes enfoques.
